centos6:
  dockerfile: Dockerfile.centos6
  build: .
  command: sh -c 'mkdir -p /tmp/pkgs && cp -a /root/rpmbuild/RPMS/x86_64/nginx-*.rpm /tmp/pkgs'
  volumes:
    - .:/tmp:rw

centos7:
  dockerfile: Dockerfile.centos7
  build: .
  command: sh -c 'mkdir -p /tmp/pkgs && cp -a /root/rpmbuild/RPMS/x86_64/nginx-*.rpm /tmp/pkgs'
  volumes:
    - .:/tmp:rw

ubuntu1404:
  dockerfile: Dockerfile.ubuntu1404
  build: .
  command: sh -c 'mkdir -p /tmp/pkgs && cp -a /usr/local/src/nginx*.deb /tmp/pkgs'
  volumes:
    - .:/tmp:rw

ubuntu1604:
  dockerfile: Dockerfile.ubuntu1604
  build: .
  command: sh -c 'mkdir -p /tmp/pkgs && cp -a /usr/local/src/nginx*.deb /tmp/pkgs'
  volumes:
    - .:/tmp:rw
